CREATE TABLE IF NOT EXISTS ACCESSTOKENENTITY
(
  ID INTEGER PRIMARY KEY NOT NULL,
  DATE_CREATED TIMESTAMP,
  DATE_UPDATED TIMESTAMP,
  PERMISSION VARCHAR(255),
  TOKEN VARCHAR(255),
  CLIENT_ID INTEGER,
  USER_ID INTEGER
);

CREATE TABLE IF NOT EXISTS AUTHCODEENTITY
(
  ID INTEGER PRIMARY KEY NOT NULL,
  DATE_CREATED TIMESTAMP,
  DATE_UPDATED TIMESTAMP,
  PERMISSION VARCHAR(255),
  CODE VARCHAR(255),
  CLIENT_ID INTEGER,
  USER_ID INTEGER
);

CREATE TABLE IF NOT EXISTS CLIENTENTITY
(
  ID INTEGER PRIMARY KEY NOT NULL,
  DATE_CREATED TIMESTAMP,
  DATE_UPDATED TIMESTAMP,
  CALLBACK VARCHAR(255),
  DESCRIPTION VARCHAR(512),
  NAME VARCHAR(255),
  SECRET VARCHAR(255),
  URL VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS USERENTITY
(
  ID INTEGER PRIMARY KEY NOT NULL,
  DATE_CREATED TIMESTAMP,
  DATE_UPDATED TIMESTAMP,
  NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS USERENTITY_ACCESSTOKENENTITY
(
  USERENTITYS_ID INTEGER NOT NULL,
  TOKENS_ID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS USERENTITY_CLIENTENTITY
(
  USERENTITYS_ID INTEGER NOT NULL,
  CLIENTS_ID INTEGER NOT NULL
);

INSERT INTO CLIENTENTITY ( NAME, SECRET, URL, CALLBACK, DESCRIPTION) VALUES
  ('A001', 'CLUB1', 'http://example.com', 'http://example.com', '1111'),
  ('A002', 'CLUB2', 'http://example.com', 'http://example.com', '2222'),
  ('A003', 'CLUB3', 'http://example.com', 'http://example.com', '3333');